message:
  name: Send message
  description: Send a message to a Vestaboard.
  fields:
    device_id:
      name: Device
      description: The Vestaboard to send the message to.
      required: true
      selector:
        device:
          integration: vestaboard
          multiple: true
      example: device_id
    message:
      name: Message
      description: The message to send.
      selector:
        text:
          multiline: true
      example: This is a message
    justify:
      name: Justify
      description: Horizontal alignment of text. Optional, default=center
      selector:
        select:
          translation_key: "justify"
          options:
            - "left"
            - "right"
            - "center"
            - "justified"
      example: left
    align:
      name: Align
      description: Vertical alignment of text. Optional, default=center
      selector:
        select:
          translation_key: "align"
          options:
            - "top"
            - "bottom"
            - "center"
            - "justified"
      example: top
    vbml:
      name: Vestaboard markup language
      description: "Compose a static or dynamic message using Vestaboard markup language. See https://docs.vestaboard.com/docs/vbml for more information."
      selector:
        text:
      example: '{ "props": { "hours": "07", "minutes": "35" }, "components": [ { "style": { "justify": "center", "align": "center" }, "template": "{{ ''{{hours}}:{{minutes}}'' }}"}]}'
    strategy:
      name: Transition strategy
      description: Transition strategy to use.
      selector:
        select:
          translation_key: strategy
          options:
            - classic
            - column
            - reverse-column
            - edges-to-center
            - row
            - diagonal
            - random
      example: column
    step_interval_ms:
      name: Step interval
      description: Step interval for the transition.
      selector:
        number:
          min: 0
          max: 3000
          unit_of_measurement: milliseconds
      example: 500
    step_size:
      name: Step size
      description: Number of columns/bits to animate at the same time for the transition.
      selector:
        number:
          min: 0
          max: 22
          unit_of_measurement: columns/bits
      example: 2
    duration:
      name: Duration
      description: Display the message temporarily. The board will revert to its previous persistent message after the duration expires.
      selector:
        number:
          min: 10
          max: 43200
          unit_of_measurement: seconds
    bypass_quiet_hours:
      name: Bypass quiet hours
      description: Ignore quiet hours setting and send the message to the Vestaboard.
      selector:
        boolean:
